pluginManagement {
    includeBuild("build-logic")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

rootProject.name = "Spyfall"

include("app")
include("features:ads")
include("features:ads:internal")
include("features:ads:ui")
include("features:blockingError")
include("features:blockingError:internal")
include("features:colorPicker")
include("features:colorPicker:internal")
include("features:forcedUpdate")
include("features:forcedUpdate:internal")
include("features:gamePlay")
include("features:gamePlay:internal")
include("features:joinGame")
include("features:joinGame:internal")
include("features:newGame")
include("features:newGame:internal")
include("features:qa")
include("features:qa:internal")
include("features:rules")
include("features:rules:internal")
include("features:settings")
include("features:settings:internal")
include("features:splash")
include("features:videoCall")
include("features:videoCall:internal")
include("features:waitingRoom")
include("features:waitingRoom:internal")
include("features:welcome")
include("features:welcome:internal")
include("libraries:common")
include("libraries:common:internal")
include("libraries:config")
include("libraries:config:internal")
include("libraries:datastore")
include("libraries:flowroutines")
include("libraries:game")
include("libraries:game:internal")
include("libraries:logging")
include("libraries:logging:internal")
include("libraries:navigation")
include("libraries:navigation:internal")
include("libraries:network")
include("libraries:network:internal")
include("libraries:resources")
include("libraries:resources:internal")
include("libraries:session")
include("libraries:session:internal")
include("libraries:test")
include("libraries:ui")
include("libraries:ui:internal")
include("libraries:test:internal")