[versions]
fragment = "1.5.0"

#plugins
detekt = "1.21.0"

[libraries]
# AndroidX
androidx-appcompat = "androidx.appcompat:appcompat:1.6.0-alpha05"
androidx-core = "androidx.core:core-ktx:1.9.0-alpha05"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-legacy-support = "androidx.legacy:legacy-support-v4:1.0.0"
androidx-lifecycle-ext = "androidx.lifecycle:lifecycle-extensions:2.2.0"
androidx-lifecycle-vm = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.0-alpha01"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.3.0-beta01"
androidx-test-junit = "androidx.test.ext:junit-ktx:1.1.3"
androidx-test-core = "androidx.test:core-ktx:1.4.0"
androidx-test-arch-core = "androidx.arch.core:core-testing:2.1.0"
androidx-test-espresso-core = "androidx.test.espresso:espresso-core:3.5.0-alpha07"
androidx-test-runner = "androidx.test:runner:1.5.0-alpha04"

androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }

arch-fragment-navigation = "android.arch.navigation:navigation-fragment:1.0.0"
arch-navigation-ui = "android.arch.navigation:navigation-ui:1.0.0"

google-play-services = "com.google.android.gms:play-services-ads:21.0.0"

coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0"
coroutines-play-servies = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.6.0"

koin-core = "io.insert-koin:koin-core:3.1.6"
koin-android = "io.insert-koin:koin-android:3.1.6"
koin-testing = "io.insert-koin:koin-test:3.1.6"
koin-junit = "io.insert-koin:koin-test-junit4:3.1.6"

hilt-android = "com.google.dagger:hilt-android:2.40.5"
hilt-compiler = "com.google.dagger:hilt-android-compiler:2.40.5"

#Firebase
firebase-database = "com.google.firebase:firebase-database:20.0.5"
firebase-firestore = "com.google.firebase:firebase-firestore:24.2.0"
firebase-storage = "com.google.firebase:firebase-storage:20.0.1"

#Testing
junit = "junit:junit:4.13.2"
roboelectric = "org.robolectric:robolectric:4.6.1"
mockito = "org.mockito:mockito-core:3.9.0"
mockito-kotlin = "com.nhaarman.mockitokotlin2:mockito-kotlin:2.2.0"
coroutines-test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.6.0"

#UI
lottie = "com.airbnb.android:lottie:3.7.0"

[plugins]