name: Android CI

on:
  pull_request:
    branches: [ master, development ]

jobs:
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: ./gradlew test

  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./gradlew assemble
      - name: Run Kotlin Linter
        run: ./gradlew ktlintStagingDebugCheck

  android_tests:
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest

