name: Create Spyfall Release Branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true

jobs:
  createrelease:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create release branch
        run: git checkout -b release-spyfall/v${{ github.event.inputs.versionName }}

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Increment version code
        run: ./scripts/increment_version_code.main.kts spyfall

      - name: Change version name
        run: ./scripts/increment_version_code.main.kts spyfall ${{ github.event.inputs.versionName }}

      - name: Commit changelog and manifest files
        id: make-commit
        run: |
          git add app_versions.properties
          git commit --message "Prepare spyfall release ${{ github.event.inputs.versionName }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Push new branch
        run: git push origin release-spyfall/v${{ github.event.inputs.versionName }}

      - name: Create pull request into main
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ github.GITHUB_TOKEN }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          head: release-spyfall/v${{ github.event.inputs.versionName }}
          base: main
          title: Spyfall v${{ github.event.inputs.versionName }} into main
          body: |
            Hi!
            This PR was created in response workflow running.
            I've updated the version name and code in commit: ${{ steps.make-commit.outputs.commit }}.
