name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'Name (lowercase) of the app to release. [spyfall | werewolf ...]'
        required: true
      versionName:
        description: 'Version being released (ie 5.5.0)'
        required: true
      versionCode:
        description: 'Version Code (ie 550). Automatically increments if not provided.'
        required: false

jobs:
  createrelease:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set the version code
        run: ./scripts/set_version_code.main.kts ${{ github.event.inputs.appName }} ${{ github.event.inputs.versionCode }}

      - name: Change version name
        run: ./scripts/set_version_name.main.kts ${{ github.event.inputs.appName }} ${{ github.event.inputs.versionName }}

      - name: Create pull request into main
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release-${{ github.event.inputs.appName }}/v${{ github.event.inputs.versionName }}
          commit-message: Prepare ${{ github.event.inputs.appName }} release ${{ github.event.inputs.versionName }}
          title: ${{ github.event.inputs.appName }} v${{ github.event.inputs.versionName }} into main
          body: |
            Hi!
            This PR was created in response workflow running.
            I've updated the version name and code in commit: ${{ steps.make-commit.outputs.commit }}.
