name: Create Spyfall Release Branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true
      versionCode:
        description: 'Version Code (ie 550)'
        required: false

jobs:
  createrelease:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set the version code
        run: ./scripts/set_version_code.main.kts spyfall ${{ github.event.inputs.versionName }}

      - name: Change version name
        run: ./scripts/set_version_name.main.kts spyfall ${{ github.event.inputs.versionName }}

      - name: Create pull request into main
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release-spyfall/v${{ github.event.inputs.versionName }}
          commit-message: Prepare spyfall release ${{ github.event.inputs.versionName }}
          title: Spyfall v${{ github.event.inputs.versionName }} into main
          body: |
            Hi!
            This PR was created in response workflow running.
            I've updated the version name and code in commit: ${{ steps.make-commit.outputs.commit }}.
