name: Pull Request Workflow

on:
  # Triggers the workflow for pull requests into any (**) base branch
  pull_request:
    branches:
      - "**"

# ensures only 1 of these workflows can exist on a PR at a time. Cancels old ones when new ones are triggered
concurrency:
  group: pr-workflow-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Update Version Codes
        run: ./scripts/set_version_code.main.kts ${{ github.run_number }}

      - name: Create Service Key Json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "service_key.json"
          json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Download Secret Files
        run: ./scripts/get_secret_files.main.kts service_key.json

      - name: Set Env Variables
        run: ./scripts/set_env_variables.main.kts ${{ github.event.pull_request.head.ref }} ${{ github.env }} ${{ github.event.pull_request.number }}

      - name: Set Up Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Copy gradle properties file
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set Up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Create Assets
        id: createassets
        run: ./scripts/create_pr_assets.kts ${{ github.env }}

      # TODO exit the create_pr_assets to sign and upload assets as well.
      - name: Sign spyfall release apk
        if: ${{ env.isSpyfallReleasePR == 'true' }}
        run: ./scripts/sign_app.main.kts ${{ env.spyfallReleaseApkPath }} ${{ secrets.KEYSTORE }} ${{ secrets.KEYSTORE_PASSWORD }} ${{ secrets.KEYALIAS }} ${{ secrets.KEY_PASSWORD }} "signedSpyfallReleaseApkPath" ${{ github.env }}

      - name: Upload spyfall release signed apk
        if: ${{ env.isSpyfallReleasePR == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: Spyfall Release Apk
          path: ${{ env.signedSpyfallReleaseApkPath }}

      - name: Sign spyfall release aab
        if: ${{ env.isSpyfallReleasePR == 'true' }}
        run: ./scripts/sign_app.main.kts ${{ env.spyfallReleaseAabPath }} ${{ secrets.KEYSTORE }} ${{ secrets.KEYSTORE_PASSWORD }} ${{ secrets.KEYALIAS }} ${{ secrets.KEY_PASSWORD }} "signedSpyfallReleaseAabPath" ${{ github.env }}

      - name: Upload spyfall release signed aab
        if: ${{ env.isSpyfallReleasePR == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: Spyfall Release aab
          path: ${{ env.signedSpyfallReleaseAabPath }}

      - name: Upload spyfall debug apk
        uses: actions/upload-artifact@v3
        with:
          name: Spyfall Debug Apk
          path: ${{ env.spyfallDebugApkPath }}

      - name: Upload werewolf debug apk
        id: uploadlastasset
        uses: actions/upload-artifact@v3
        with:
          name: Werewolf Debug Apk
          path: ${{ env.werewolfDebugApkPath }}

      - name: Sign Werewolf release apk
        if: ${{ env.isWerewolfReleasePR == 'true' }}
        run: ./scripts/sign_app.main.kts ${{ env.werewolfReleaseApkPath }} ${{ secrets.KEYSTORE }} ${{ secrets.KEYSTORE_PASSWORD }} ${{ secrets.KEYALIAS }} ${{ secrets.KEY_PASSWORD }} "signedWerewolfReleaseApkPath" ${{ github.env }}

      - name: Upload werewolf release signed apk
        if: ${{ env.isWerewolfReleasePR == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: Werewolf Release Apk
          path: ${{ env.signedWerewolfReleaseApkPath }}

      - name: Sign Werewolf release aab
        if: ${{ env.isWerewolfReleasePR == 'true' }}
        run: ./scripts/sign_app.main.kts ${{ env.werewolfReleaseAabPath }} ${{ secrets.KEYSTORE }} ${{ secrets.KEYSTORE_PASSWORD }} ${{ secrets.KEYALIAS }} ${{ secrets.KEY_PASSWORD }} "signedSWerewolfReleaseAabPath" ${{ github.env }}

      - name: Upload werewolf release signed aab
        if: ${{ env.isWerewolfReleasePR == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: Werewolf Release Aab
          path: ${{ env.signedSWerewolfReleaseAabPath }}

      - name: Deploy Spyfall Assets to Firebase
        run: ./scripts/deploy_app_distribution.main.kts "spyfall" ${{ github.env }} ${{ env.spyfallDebugApkPath }}

      - name: Deploy Spyfall Release Asset to Firebase
        if: ${{ env.isSpyfallReleasePR == 'true' }}
        run: ./scripts/deploy_app_distribution.main.kts "spyfall" ${{ github.env }} ${{ env.spyfallReleaseApkPath }}

      - name: Update Spyfall Draft Release
        uses: softprops/action-gh-release@v1
        if: ${{ env.isSpyfallReleasePR == 'true' }}
        with:
          tag_name: ${{ env.releaseTagName }}
          draft: true
          release_notes: ${{ env.releaseNotes }}
          name: Spyfall Release ${{ env.releaseVersion}}
          files: |
            ${{ env.signedSpyfallReleaseAabPath }}
            ${{ env.signedSpyfallReleaseApkPath }}
            ${{ env.spyfallDebugApkPath }}

      - name: Update Werewolf Draft Release
        uses: softprops/action-gh-release@v1
        if: ${{ env.isWerewolfReleasePR == 'true' }}
        with:
          tag_name: ${{ env.releaseTagName }}
          release_notes: ${{ env.releaseNotes }}
          name: Werewolf Release ${{ env.releaseVersion}}
          draft: true
          files: |
            ${{ env.signedWerewolfReleaseAabPath }}
            ${{ env.signedWerewolfReleaseApkPath }}
            ${{ env.werewolfDebugApkPath }}

      - name: Deploy Werewolf Debug Asset to Firebase
        run: ./scripts/deploy_app_distribution.main.kts "werewolf" ${{ github.env }} ${{ env.werewolfDebugApkPath }}

      - name: Deploy Werewolf Release Asset to Firebase
        if: ${{ env.isWerewolfReleasePR == 'true' }}
        run: ./scripts/deploy_app_distribution.main.kts "werewolf" ${{ github.env }} ${{ env.werewolfReleaseApkPath }}

      - name: Update artifacts comment on PR
        run: ./scripts/update_pr_comment.main.kts "${GITHUB_REPOSITORY}" ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.number }} "${GITHUB_RUN_ID}" ${{ github.env }} ${{ env.releaseTagName }}

  style:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Create service key json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "service_key.json"
          json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Download secret files
        run: ./scripts/get_secret_files.main.kts service_key.json

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Detekt All
        run: ./gradlew detektAll

      - name: Checkstyle
        run: ./gradlew checkstyleAll

  test:
    runs-on: macos-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Create service key json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "service_key.json"
          json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Download secret files
        run: ./scripts/get_secret_files.main.kts service_key.json

      - name: Set Up Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Copy  gradle properties file
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Unit tests
        run: ./gradlew test --stacktrace
