name: Pull Request Workflow

on:
  # Triggers the workflow for pull requests into any (**) base branch
  pull_request:
    branches:
      - "**"

# ensures only 1 of these workflows can exist on a PR at a time. Cancels old ones when new ones are triggered
concurrency:
  group: pr-workflow-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set Release Env Variables
        if: contains(github.head_ref, 'release')
        run: ./scripts/set_env_release_version.main.kts ${{ github.head_ref }} $GITHUB_ENV

      - name: Create Service Key Json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "service_key.json"
          json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Download Secret Files
        run: ./scripts/get_secret_files.main.kts service_key.json

      - name: Set Up Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Copy gradle properties file
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set Up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Create Assets
        id: createassets
        run: ./scripts/create_pr_assets.kts $GITHUB_ENV ${{ env.isSpyfallReleasePR }} ${{ env.isWerewolfReleasePR }}

      # TODO exit the create_pr_assets to sign and upload assets as well.
      - name: Sign spyfall legacy release apk
        if: ${{ env.isSpyfallReleasePR == 'true' }}
        run: ./scripts/sign_app.main.kts ${{ env.spyfallLegacyReleaseApkPath }} ${{ secrets.KEYSTORE }} ${{ secrets.KEYSTORE_PASSWORD }} ${{ secrets.KEYALIAS }} ${{ secrets.KEY_PASSWORD }} "signedSpyfallLegacyReleaseApkPath" $GITHUB_ENV

      - name: Upload spyfall legacy release signed apk
        if: ${{ env.isSpyfallReleasePR == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: Spyfall Legacy Release Apk
          path: ${{ env.signedSpyfallLegacyReleaseApkPath }}

      - name: Sign spyfall refactor release apk
        if: ${{ env.isSpyfallReleasePR == 'true' }}
        run: ./scripts/sign_app.main.kts ${{ env.spyfallRefactorReleaseApkPath }} ${{ secrets.KEYSTORE }} ${{ secrets.KEYSTORE_PASSWORD }} ${{ secrets.KEYALIAS }} ${{ secrets.KEY_PASSWORD }} "signedSpyfallRefactorReleaseApkPath" $GITHUB_ENV

      - name: Upload spyfall refactor release signed apk
        if: ${{ env.isSpyfallReleasePR == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: Spyfall Refactor Release Apk
          path: ${{ env.signedSpyfallRefactorReleaseApkPath }}

      - name: Sign spyfall legacy release aab
        if: ${{ env.isSpyfallReleasePR == 'true' }}
        run: ./scripts/sign_app.main.kts ${{ env.spyfallLegacyReleaseAabPath }} ${{ secrets.KEYSTORE }} ${{ secrets.KEYSTORE_PASSWORD }} ${{ secrets.KEYALIAS }} ${{ secrets.KEY_PASSWORD }} "signedSpyfallLegacyReleaseAabPath" $GITHUB_ENV

      - name: Upload spyfall legacy release signed aab
        if: ${{ env.isSpyfallReleasePR == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: Spyfall Legacy Release aab
          path: ${{ env.signedSpyfallLegacyReleaseAabPath }}

      - name: Sign spyfall refactor release aab
        if: ${{ env.isSpyfallReleasePR == 'true' }}
        run: ./scripts/sign_app.main.kts ${{ env.spyfallRefactorReleaseAabPath }} ${{ secrets.KEYSTORE }} ${{ secrets.KEYSTORE_PASSWORD }} ${{ secrets.KEYALIAS }} ${{ secrets.KEY_PASSWORD }} "signedSpyfallRefactorReleaseAabPath" $GITHUB_ENV

      - name: Upload spyfall refactor release signed aab
        if: ${{ env.isSpyfallReleasePR == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: Spyfall Refactor Release aab
          path: ${{ env.signedSpyfallRefactorReleaseAabPath }}

      - name: Upload spyfall legacy debug apk
        uses: actions/upload-artifact@v3
        with:
          name: Spyfall Legacy Debug Apk
          path: ${{ env.spyfallLegacyDebugApkPath }}

      - name: Upload spyfall refactor debug apk
        uses: actions/upload-artifact@v3
        with:
          name: Spyfall Refactor Debug Apk
          path: ${{ env.spyfallRefactorDebugApkPath }}

      - name: Upload werewolf debug apk
        id: uploadlastasset
        uses: actions/upload-artifact@v3
        with:
          name: Werewolf Debug Apk
          path: ${{ env.werewolfDebugApkPath }}

      - name: Sign Werewolf release apk
        if: ${{ env.isWerewolfReleasePR == 'true' }}
        run: ./scripts/sign_app.main.kts ${{ env.werewolfReleaseApkPath }} ${{ secrets.KEYSTORE }} ${{ secrets.KEYSTORE_PASSWORD }} ${{ secrets.KEYALIAS }} ${{ secrets.KEY_PASSWORD }} "signedWerewolfReleaseApkPath" $GITHUB_ENV

      - name: Upload werewolf release signed apk
        if: ${{ env.isWerewolfReleasePR == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: Werewolf Release Apk
          path: ${{ env.signedWerewolfReleaseApkPath }}

      - name: Sign Werewolf release aab
        if: ${{ env.isWerewolfReleasePR == 'true' }}
        run: ./scripts/sign_app.main.kts ${{ env.werewolfReleaseAabPath }} ${{ secrets.KEYSTORE }} ${{ secrets.KEYSTORE_PASSWORD }} ${{ secrets.KEYALIAS }} ${{ secrets.KEY_PASSWORD }} "signedSWerewolfReleaseAabPath" $GITHUB_ENV

      - name: Upload werewolf release signed aab
        if: ${{ env.isWerewolfReleasePR == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: Werewolf Release Aab
          path: ${{ env.signedSWerewolfReleaseAabPath }}

      - name: Update Spyfall Draft Release
        uses: softprops/action-gh-release@v1
        if: ${{ env.isSpyfallReleasePR == 'true' }}
        with:
          tag_name: $GITHUB_REF_NAME
          draft: true
          name: Spyfall Release ${{ env.releaseVersion}}
          files: |
            ${{ env.signedSpyfallRefactorReleaseAabPath }}
            ${{ env.signedSpyfallLegacyReleaseAabPath }}
            ${{ env.signedSpyfallRefactorReleaseApkPath }}
            ${{ env.signedSpyfallLegacyReleaseApkPath }}
            ${{ env.spyfallRefactorDebugApkPath }}
            ${{ env.spyfallLegacyDebugApkPath }}

      - name: Update Werewolf Draft Release
        uses: softprops/action-gh-release@v1
        if: ${{ env.isWerewolfReleasePR == 'true' }}
        with:
          tag_name: $GITHUB_REF_NAME
          name: Werewolf Release ${{ env.releaseVersion}}
          draft: true
          files: |
            ${{ env.signedWerewolfReleaseAabPath }}
            ${{ env.signedWerewolfReleaseApkPath }}
            ${{ env.werewolfDebugApkPath }}

      - name: Update artifacts comment on PR
        run: ./scripts/update_pr_comment.main.kts "${GITHUB_REPOSITORY}" ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.number }} "${GITHUB_RUN_ID}"

  style:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Create service key json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "service_key.json"
          json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Download secret files
        run: ./scripts/get_secret_files.main.kts service_key.json

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Detekt All
        run: ./gradlew detektAll

      - name: Checkstyle
        run: ./gradlew checkstyleAll

  test:
    runs-on: macos-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Create service key json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "service_key.json"
          json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Download secret files
        run: ./scripts/get_secret_files.main.kts service_key.json

      - name: Set Up Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Copy  gradle properties file
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Unit tests
        run: ./gradlew test --stacktrace
