name: Pull Request Workflow

on:
  # Triggers the workflow for pull requests into any (**) base branch
  pull_request:
    branches:
      - "**"

# ensures only 1 of these workflows can exist on a PR at a time. Cancels old ones when new ones are triggered
concurrency:
  group: pr-workflow-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    env:
      isWerewolfReleasePR: ""
      isSpyfallReleasePR: ""
      releaseVersion: ""
      releaseTagName: ""
      spyfallAppId: ""
      werewolfAppId: ""
      spyfallFirebaseDistributionLink: ""
      werewolfFirebaseDistributionLink: ""
      releaseNotesFile: ""
      spyfallDebugApkPath: ""
      werewolfDebugApkPath: ""
      spyfallReleaseApkPath: ""
      werewolfReleaseApkPath: ""
      spyfallReleaseAabPath: ""
      werewolfReleaseAabPath: ""
      pullRequestLink: ""
      GOOGLE_APPLICATION_CREDENTIALS: "apps/spyfall/service-account-key.json"
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Update Version Codes
        run: ./scripts/ci/set_version_code.main.kts ${{ github.run_number }}

      - name: Create Service Key Json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "service_key.json"
          json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Download Secret Files
        run: ./scripts/get_secret_files.main.kts service_key.json

      - name: Set Env Variables
        run: ./scripts/ci/set_pr_env_variables.main.kts ${{ github.event.pull_request.head.ref }} ${{ github.env }} ${{ github.event.pull_request.number }}

      - name: Set Up Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Copy Gradle Properties File
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set Up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Create Assets
        id: createassets
        run: ./scripts/ci/create_pr_assets.main.kts ${{ env.isSpyfallReleasePR }} ${{ env.isWerewolfReleasePR }} ${{ github.env }}  ${{ secrets.KEYSTORE }} ${{ secrets.KEYSTORE_PASSWORD }} ${{ secrets.KEYALIAS }} ${{ secrets.KEY_PASSWORD }}

      - name: Upload Spyfall Release Signed Apk
        if: ${{ env.isSpyfallReleasePR == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: Spyfall Release Apk
          path: ${{ env.spyfallReleaseApkPath }}

      - name: Upload Spyfall Release Signed Aab
        if: ${{ env.isSpyfallReleasePR == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: Spyfall Release aab
          path: ${{ env.spyfallReleaseAabPath }}

      - name: Upload Spyfall Debug Apk
        uses: actions/upload-artifact@v3
        with:
          name: Spyfall Debug Apk
          path: ${{ env.spyfallDebugApkPath }}

      - name: Upload Werewolf Debug Apk
        id: uploadlastasset
        uses: actions/upload-artifact@v3
        with:
          name: Werewolf Debug Apk
          path: ${{ env.werewolfDebugApkPath }}

      - name: Upload Werewolf Release Signed Apk
        if: ${{ env.isWerewolfReleasePR == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: Werewolf Release Apk
          path: ${{ env.werewolfReleaseApkPath }}

      - name: Upload Werewolf Release Signed Aab
        if: ${{ env.isWerewolfReleasePR == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: Werewolf Release Aab
          path: ${{ env.werewolfReleaseAabPath }}

      - name: Deploy Spyfall Debug Asset to Firebase
        run: ./scripts/ci/deploy_app_distribution.main.kts "spyfall" ${{ env.spyfallAppId }} ${{ secrets.FIREBASE_TOKEN }} ${{ github.env }} ${{ env.pullRequestLink }} false ${{ env.spyfallDebugApkPath }}

      - name: Deploy Spyfall Release Asset to Firebase
        if: ${{ env.isSpyfallReleasePR == 'true' }}
        run: ./scripts/ci/deploy_app_distribution.main.kts "spyfall" ${{ env.spyfallAppId }} ${{ secrets.FIREBASE_TOKEN }} ${{ github.env }} ${{ env.pullRequestLink }} true ${{ env.spyfallReleaseApkPath }}

      - name: Update Spyfall Draft Release
        if: ${{ env.isSpyfallReleasePR == 'true' }}
        run: ./scripts/ci/update_release_draft.main.kts "${GITHUB_REPOSITORY}" ${{ secrets.GITHUB_TOKEN }} ${{ env.releaseTagName }} ${{ env.releaseNotesFile }} ${{ env.spyfallReleaseAabPath }} ${{ env.spyfallReleaseApkPath }} ${{ env.spyfallDebugApkPath }}

      - name: Update Werewolf Draft Release
        if: ${{ env.isWerewolfReleasePR == 'true' }}
        run: ./scripts/ci/update_release_draft.main.kts "${GITHUB_REPOSITORY}" ${{ secrets.GITHUB_TOKEN }} ${{ env.releaseTagName }} ${{ env.releaseNotesFile }} ${{ env.werewolfReleaseAabPath }} ${{ env.werewolfReleaseApkPath }} ${{ env.werewolfDebugApkPath }}

      - name: Deploy Werewolf Debug Asset to Firebase
        run: ./scripts/ci/deploy_app_distribution.main.kts "werewolf" ${{ env.werewolfAppId }} ${{ secrets.FIREBASE_TOKEN }} ${{ github.env }} ${{ env.pullRequestLink }} false ${{ env.werewolfDebugApkPath }}

      - name: Deploy Werewolf Release Asset to Firebase
        if: ${{ env.isWerewolfReleasePR == 'true' }}
        run: ./scripts/ci/deploy_app_distribution.main.kts "werewolf" ${{ env.werewolfAppId }} ${{ secrets.FIREBASE_TOKEN }} ${{ github.env }} ${{ env.pullRequestLink }} true ${{ env.werewolfReleaseApkPath }}

      - name: Update PR Comment
        run: ./scripts/ci/update_pr_comment.main.kts "${GITHUB_REPOSITORY}" ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.number }} "${GITHUB_RUN_ID}" ${{ env.spyfallFirebaseDistributionLink }} ${{ env.werewolfFirebaseDistributionLink }} ${{ github.run_number }} ${{ env.releaseTagName }}

  style:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Create service key json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "service_key.json"
          json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Download secret files
        run: ./scripts/get_secret_files.main.kts service_key.json

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Detekt All
        run: ./gradlew detektAll

      - name: Checkstyle
        run: ./gradlew checkstyleAll

  test:
    runs-on: macos-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Create service key json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "service_key.json"
          json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Download secret files
        run: ./scripts/get_secret_files.main.kts service_key.json

      - name: Set Up Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Copy  gradle properties file
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Unit tests
        run: ./gradlew test --stacktrace
