name: Release PR Workflow

on:
  # Triggers the workflow on every pull request
  pull_request:
    branches:
      - "release-spyfall/v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# ensures only 1 of these workflows can exist on a PR at a time. Cancels old ones when new ones are triggered
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Job
        run: echo "should be ran on RELEASE pr"
