name: Build and Upload Spyfall Assets

on:
  # Triggers the workflow on every pull request
  pull_request:
    branches:
      - "release-spyfall/*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  name: Print
  run: echo Printing this thing
