name: Publish Spyfall

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Make file tree script executable
        run: chmod +x scripts/print-file-tree.sh
        shell: bash

      - name: Print file tree
        run: ./scripts/print-file-tree.sh
        shell: bash

      - name: Download aab artifact
      - uses: actions/download-artifact@v3
        with:
          name: app-release-signed.aab

      - name: Publish To Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_KEY }}
          packageName: com.dangerfield.spyfall.free
          releaseFiles: apps/spyfall/build/outputs/bundle/LegacyRelease/app-release-signed.aab
          track: production
          status: inProgress
          inAppUpdatePriority: 0
          userFraction: 0.33
